# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product_image_analyzer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'product_image_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproduct_image_analyzer.proto\"E\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"$\n\x0fImageUrlRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\"3\n\rImageResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\x84\x01\n\x14ProductImageAnalyzer\x12\x32\n\x11GenerateFromImage\x12\r.ImageRequest\x1a\x0e.ImageResponse\x12\x38\n\x14GenerateFromImageUrl\x12\x10.ImageUrlRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_image_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=32
  _globals['_IMAGEREQUEST']._serialized_end=101
  _globals['_IMAGEURLREQUEST']._serialized_start=103
  _globals['_IMAGEURLREQUEST']._serialized_end=139
  _globals['_IMAGERESPONSE']._serialized_start=141
  _globals['_IMAGERESPONSE']._serialized_end=192
  _globals['_PRODUCTIMAGEANALYZER']._serialized_start=195
  _globals['_PRODUCTIMAGEANALYZER']._serialized_end=327
# @@protoc_insertion_point(module_scope)
