# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\x0cimageservice\"R\n\x13ProcessImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x14\n\x0cproduct_name\x18\x03 \x01(\t\"X\n\x14ProcessImageResponse\x12\x1c\n\x14processed_image_data\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2e\n\x0cImageService\x12U\n\x0cProcessImage\x12!.imageservice.ProcessImageRequest\x1a\".imageservice.ProcessImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROCESSIMAGEREQUEST']._serialized_start=37
  _globals['_PROCESSIMAGEREQUEST']._serialized_end=119
  _globals['_PROCESSIMAGERESPONSE']._serialized_start=121
  _globals['_PROCESSIMAGERESPONSE']._serialized_end=209
  _globals['_IMAGESERVICE']._serialized_start=211
  _globals['_IMAGESERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
