# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.grpc import image_service_pb2


class ImageServiceStub(object):
    """Service definition for image processing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessImage = channel.unary_unary(
                '/imageservice.ImageService/ProcessImage',
                request_serializer=image_service_pb2.ProcessImageRequest.SerializeToString,
                response_deserializer=image_service_pb2.ProcessImageResponse.FromString,
                )


class ImageServiceServicer(object):
    """Service definition for image processing
    """

    def ProcessImage(self, request, context):
        """Process an image and return the processed image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=image_service_pb2.ProcessImageRequest.FromString,
                    response_serializer=image_service_pb2.ProcessImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageservice.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Service definition for image processing
    """

    @staticmethod
    def ProcessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageservice.ImageService/ProcessImage',
            image_service_pb2.ProcessImageRequest.SerializeToString,
            image_service_pb2.ProcessImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
