# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import seo_agent_pb2 as seo__agent__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in seo_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SEOAgentServiceStub(object):
    """The SEO Agent service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/seo_agent.SEOAgentService/HealthCheck',
                request_serializer=seo__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=seo__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.AnalyzeSEO = channel.unary_unary(
                '/seo_agent.SEOAgentService/AnalyzeSEO',
                request_serializer=seo__agent__pb2.AnalyzeSEORequest.SerializeToString,
                response_deserializer=seo__agent__pb2.AnalyzeSEOResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/seo_agent.SEOAgentService/Chat',
                request_serializer=seo__agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=seo__agent__pb2.ChatResponse.FromString,
                _registered_method=True)


class SEOAgentServiceServicer(object):
    """The SEO Agent service definition
    """

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSEO(self, request, context):
        """Analyze image for SEO purposes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """General chat endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SEOAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=seo__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=seo__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'AnalyzeSEO': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSEO,
                    request_deserializer=seo__agent__pb2.AnalyzeSEORequest.FromString,
                    response_serializer=seo__agent__pb2.AnalyzeSEOResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=seo__agent__pb2.ChatRequest.FromString,
                    response_serializer=seo__agent__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seo_agent.SEOAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seo_agent.SEOAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SEOAgentService(object):
    """The SEO Agent service definition
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seo_agent.SEOAgentService/HealthCheck',
            seo__agent__pb2.HealthCheckRequest.SerializeToString,
            seo__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeSEO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seo_agent.SEOAgentService/AnalyzeSEO',
            seo__agent__pb2.AnalyzeSEORequest.SerializeToString,
            seo__agent__pb2.AnalyzeSEOResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seo_agent.SEOAgentService/Chat',
            seo__agent__pb2.ChatRequest.SerializeToString,
            seo__agent__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
