# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seo_agent.proto
# Protobuf Python Version: 4.x
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fseo_agent.proto\x12\tseo_agent\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"&\n\x11\x41nalyzeSEORequest\x12\x11\n\timage_url\x18\x01 \x01(\t\"u\n\x12\x41nalyzeSEOResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\timage_url\x18\x02 \x01(\t\x12\x10\n\x08\x61nalysis\x18\x03 \x01(\t\x12\x1a\n\x12intermediate_steps\x18\x04 \x03(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"\x1e\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\\\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x1a\n\x12intermediate_steps\x18\x03 \x03(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xe3\x01\n\x0fSEOAgentService\x12L\n\x0bHealthCheck\x12\x1d.seo_agent.HealthCheckRequest\x1a\x1e.seo_agent.HealthCheckResponse\x12I\n\nAnalyzeSEO\x12\x1c.seo_agent.AnalyzeSEORequest\x1a\x1d.seo_agent.AnalyzeSEOResponse\x12\x37\n\x04\x43hat\x12\x16.seo_agent.ChatRequest\x1a\x17.seo_agent.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seo_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=30
  _globals['_HEALTHCHECKREQUEST']._serialized_end=50
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=52
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=106
  _globals['_ANALYZESEOREQUEST']._serialized_start=108
  _globals['_ANALYZESEOREQUEST']._serialized_end=146
  _globals['_ANALYZESEORESPONSE']._serialized_start=148
  _globals['_ANALYZESEORESPONSE']._serialized_end=265
  _globals['_CHATREQUEST']._serialized_start=267
  _globals['_CHATREQUEST']._serialized_end=297
  _globals['_CHATRESPONSE']._serialized_start=299
  _globals['_CHATRESPONSE']._serialized_end=391
  _globals['_SEOAGENTSERVICE']._serialized_start=394
  _globals['_SEOAGENTSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
