// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/proto/image-service/image_service.proto

package image_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message containing the input image
type ProcessImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`       // Raw image bytes
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`          // MIME type of the image (e.g., "image/jpeg", "image/png")
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // Optional product name for context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImageRequest) Reset() {
	*x = ProcessImageRequest{}
	mi := &file_internal_proto_image_service_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageRequest) ProtoMessage() {}

func (x *ProcessImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_image_service_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageRequest.ProtoReflect.Descriptor instead.
func (*ProcessImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_image_service_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ProcessImageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ProcessImageRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

// Response message containing the processed image
type ProcessImageResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProcessedImageData []byte                 `protobuf:"bytes,1,opt,name=processed_image_data,json=processedImageData,proto3" json:"processed_image_data,omitempty"` // Processed image bytes
	MimeType           string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`                                 // MIME type of the processed image
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                   // Optional message or status
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessImageResponse) Reset() {
	*x = ProcessImageResponse{}
	mi := &file_internal_proto_image_service_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageResponse) ProtoMessage() {}

func (x *ProcessImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_image_service_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageResponse.ProtoReflect.Descriptor instead.
func (*ProcessImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_image_service_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessImageResponse) GetProcessedImageData() []byte {
	if x != nil {
		return x.ProcessedImageData
	}
	return nil
}

func (x *ProcessImageResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ProcessImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_image_service_image_service_proto protoreflect.FileDescriptor

const file_internal_proto_image_service_image_service_proto_rawDesc = "" +
	"\n" +
	"0internal/proto/image-service/image_service.proto\x12\fimageservice\"t\n" +
	"\x13ProcessImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\"\x7f\n" +
	"\x14ProcessImageResponse\x120\n" +
	"\x14processed_image_data\x18\x01 \x01(\fR\x12processedImageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2e\n" +
	"\fImageService\x12U\n" +
	"\fProcessImage\x12!.imageservice.ProcessImageRequest\x1a\".imageservice.ProcessImageResponseB+Z)stox-gateway/internal/proto/image-serviceb\x06proto3"

var (
	file_internal_proto_image_service_image_service_proto_rawDescOnce sync.Once
	file_internal_proto_image_service_image_service_proto_rawDescData []byte
)

func file_internal_proto_image_service_image_service_proto_rawDescGZIP() []byte {
	file_internal_proto_image_service_image_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_image_service_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_image_service_image_service_proto_rawDesc), len(file_internal_proto_image_service_image_service_proto_rawDesc)))
	})
	return file_internal_proto_image_service_image_service_proto_rawDescData
}

var file_internal_proto_image_service_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_image_service_image_service_proto_goTypes = []any{
	(*ProcessImageRequest)(nil),  // 0: imageservice.ProcessImageRequest
	(*ProcessImageResponse)(nil), // 1: imageservice.ProcessImageResponse
}
var file_internal_proto_image_service_image_service_proto_depIdxs = []int32{
	0, // 0: imageservice.ImageService.ProcessImage:input_type -> imageservice.ProcessImageRequest
	1, // 1: imageservice.ImageService.ProcessImage:output_type -> imageservice.ProcessImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_image_service_image_service_proto_init() }
func file_internal_proto_image_service_image_service_proto_init() {
	if File_internal_proto_image_service_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_image_service_image_service_proto_rawDesc), len(file_internal_proto_image_service_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_image_service_image_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_image_service_image_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_image_service_image_service_proto_msgTypes,
	}.Build()
	File_internal_proto_image_service_image_service_proto = out.File
	file_internal_proto_image_service_image_service_proto_goTypes = nil
	file_internal_proto_image_service_image_service_proto_depIdxs = nil
}
